/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RedoHer.View;
import RedoHer.Controller.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author septa
 */
public class FormWarnet extends javax.swing.JFrame {

    /**
     * Creates new form FormWarnet
     */
    private WarnetController con;
    public FormWarnet()  {
        try {
            initComponents();
            con = new WarnetController(this);
            con.bersih();
            con.tampil();
        } catch (Exception ex) {
            Logger.getLogger(FormWarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public javax.swing.JTextField getTxtkode(){
        return txtkode;
    }
    public javax.swing.JTextField getTxtnama(){
        return txtnama;
    }
    public javax.swing.JTextField getTxttglmasuk(){
        return txttglmasuk;
    }
    
    public javax.swing.JTextField getTxtjammasuk(){
        return txtjammasuk;
    }
    public javax.swing.JTextField getTxtjamkeluar(){
        return txtjamkeluar;
    }
    public javax.swing.JTextField getTxttarif(){
        return txttarif;
    }
    public javax.swing.JTable getTblwarnet(){
        return tblwarnet;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttglmasuk = new javax.swing.JTextField();
        txtjammasuk = new javax.swing.JTextField();
        txttarif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblwarnet = new javax.swing.JTable();
        btnhitung = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtjamkeluar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("kodepel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(21, 20, 50, 16);

        jLabel2.setText("namapel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 60, 16);

        jLabel4.setText("tglmasuk");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 80, 60, 16);

        jLabel5.setText("jammasuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 60, 16);

        jLabel6.setText("tarif");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 60, 16);
        getContentPane().add(txtkode);
        txtkode.setBounds(100, 20, 350, 30);
        getContentPane().add(txtnama);
        txtnama.setBounds(100, 50, 350, 30);

        txttglmasuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttglmasukFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttglmasukFocusLost(evt);
            }
        });
        txttglmasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttglmasukKeyPressed(evt);
            }
        });
        getContentPane().add(txttglmasuk);
        txttglmasuk.setBounds(100, 80, 350, 30);

        txtjammasuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtjammasukFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtjammasukFocusLost(evt);
            }
        });
        getContentPane().add(txtjammasuk);
        txtjammasuk.setBounds(100, 110, 350, 30);

        txttarif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttarifFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttarifFocusLost(evt);
            }
        });
        getContentPane().add(txttarif);
        txttarif.setBounds(100, 170, 350, 30);

        tblwarnet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "kodepel", "namapel", "tglmasuk", "jammasuk", "jamkeluar", "lama", "tarif", "diskon", "total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblwarnet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblwarnetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblwarnet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 20, 720, 210);

        btnhitung.setText("hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnhitung);
        btnhitung.setBounds(100, 220, 72, 23);

        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(100, 260, 72, 23);

        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(200, 260, 72, 23);

        btncancel.setText("cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(300, 260, 72, 23);

        jLabel7.setText("jamkeluar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 140, 60, 16);

        txtjamkeluar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtjamkeluarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtjamkeluarFocusLost(evt);
            }
        });
        getContentPane().add(txtjamkeluar);
        txtjamkeluar.setBounds(100, 140, 350, 30);

        setSize(new java.awt.Dimension(1219, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        try {
            // TODO add your handling code here:
            con.insert();
            con.tampil();
            con.bersih();
        } catch (Exception ex) {
            Logger.getLogger(FormWarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            // TODO add your handling code here:
            con.update();
            con.tampil();
            con.bersih();
        } catch (Exception ex) {
            Logger.getLogger(FormWarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            // TODO add your handling code here:
            con.delete();
            con.tampil();
            con.bersih();
        } catch (Exception ex) {
            Logger.getLogger(FormWarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        try {
            // TODO add your handling code here:
            con.bersih();
        } catch (Exception ex) {
            Logger.getLogger(FormWarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncancelActionPerformed

    private void tblwarnetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblwarnetMouseClicked
        // TODO add your handling code here:
        con.tableklik();
    }//GEN-LAST:event_tblwarnetMouseClicked

    private void txttglmasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttglmasukKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttglmasukKeyPressed

    private void txttglmasukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttglmasukFocusGained
        // TODO add your handling code here:
        if(txttglmasuk.getText().equals("yyyy-mm-dd")){
            txttglmasuk.setText("");
        }
    }//GEN-LAST:event_txttglmasukFocusGained

    private void txttglmasukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttglmasukFocusLost
        // TODO add your handling code here:
         if(txttglmasuk.getText().equals("")){
            txttglmasuk.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_txttglmasukFocusLost

    private void txtjammasukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjammasukFocusGained
        // TODO add your handling code here:
        if(txtjammasuk.getText().equals("HH:dd")){
            txtjammasuk.setText("");
        }
    }//GEN-LAST:event_txtjammasukFocusGained

    private void txtjammasukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjammasukFocusLost
        // TODO add your handling code here:
        if(txtjammasuk.getText().equals("")){
            txtjammasuk.setText("HH:dd");
        }
    }//GEN-LAST:event_txtjammasukFocusLost

    private void txttarifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttarifFocusGained
        // TODO add your handling code here:
          if(txttarif.getText().equals("HH")){
            txttarif.setText("");
        }
    }//GEN-LAST:event_txttarifFocusGained

    private void txttarifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttarifFocusLost
        // TODO add your handling code here:
         if(txttarif.getText().equals("")){
            txttarif.setText("HH");
        }
    }//GEN-LAST:event_txttarifFocusLost

    private void txtjamkeluarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjamkeluarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamkeluarFocusGained

    private void txtjamkeluarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjamkeluarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamkeluarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWarnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblwarnet;
    private javax.swing.JTextField txtjamkeluar;
    private javax.swing.JTextField txtjammasuk;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttarif;
    private javax.swing.JTextField txttglmasuk;
    // End of variables declaration//GEN-END:variables

    public Object getTx() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
