/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Redho060523.view;
import Redho060523.Controller.GajiController;
/**
 *
 * @author septa
 */
public class FormGaji extends javax.swing.JFrame{

    /**
     * Creates new form FormGaji
     */
    GajiController controller;
        public FormGaji() {
            initComponents();
            controller = new GajiController(this);
            controller.isiCombo();
            controller.bersihForm();
            controller.tampilData();
    }
    public javax.swing.JComboBox getcbokaryawan(){
        return cbokaryawan;
    }
    public javax.swing.JTextField getTxtTahun(){
        return txttahun;
    }
    public javax.swing.JTextField getTxtBulan(){
        return txtbulan;
    }
    public javax.swing.JTable getTblgaji(){
        return tblgaji;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbokaryawan = new javax.swing.JComboBox<>();
        txttahun = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgaji = new javax.swing.JTable();
        btnmasukangaji = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtbulan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        getContentPane().setLayout(null);

        jLabel1.setText("Karyawan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 51, 16);

        cbokaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbokaryawan);
        cbokaryawan.setBounds(80, 40, 110, 22);

        txttahun.setText("jTextField2");
        txttahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttahunActionPerformed(evt);
            }
        });
        getContentPane().add(txttahun);
        txttahun.setBounds(80, 70, 110, 22);

        tblgaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Karyawan", "Nip", "Bulan", "Tahun", "Gajipokok", "Tjgnanak", "Tjgnistri", "TotalGaji"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgajiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblgaji);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(78, 227, 486, 150);

        btnmasukangaji.setText("Masukan Gaji");
        btnmasukangaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukangajiActionPerformed(evt);
            }
        });
        getContentPane().add(btnmasukangaji);
        btnmasukangaji.setBounds(210, 100, 101, 23);

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(80, 170, 72, 23);

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(260, 170, 72, 23);

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(170, 170, 72, 23);

        jLabel8.setText("Tahun");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 70, 33, 16);

        txtbulan.setText("jTextField7");
        txtbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbulanActionPerformed(evt);
            }
        });
        getContentPane().add(txtbulan);
        txtbulan.setBounds(80, 100, 110, 22);

        jLabel9.setText("Bulan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 100, 30, 16);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(80, 148, 590, 3);

        setSize(new java.awt.Dimension(686, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblgajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgajiMouseClicked
        // TODO add your handling code here:
        controller.getGaji();
    }//GEN-LAST:event_tblgajiMouseClicked

    private void txttahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttahunActionPerformed

    private void txtbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbulanActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteGaji();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        controller.updateGaji();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
         controller.bersihForm();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnmasukangajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukangajiActionPerformed
        // TODO add your handling code here:
        controller.saveGaji();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_btnmasukangajiActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnmasukangaji;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbokaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblgaji;
    private javax.swing.JTextField txtbulan;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables

}
